name: Send Daily Poems

on:
  schedule:
    - cron: "0 2 * * *"  # Every day at 2 AM UTC
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger poem cron via HTTP
        run: |
          curl -X GET "https://grub-poem-ai.onrender.com/run-poem-cron?key=${{ secrets.CRON_SECRET_KEY }}"
